apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
spec:
  selector:
    matchLabels:
      app: template
  replicas: 3
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: template:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 8080
