CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pkey
            PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name       VARCHAR                  NULL,
    email      VARCHAR                  NULL
        CONSTRAINT users_email_key
            UNIQUE
);

CREATE TABLE auths
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT auths_pkey
            PRIMARY KEY,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    source        VARCHAR                  NOT NULL,
    source_id     VARCHAR                  NOT NULL,
    access_token  VARCHAR                  NOT NULL,
    refresh_token VARCHAR                  NOT NULL,
    expiry        TIMESTAMP WITH TIME ZONE NULL,
    user_id       BIGINT
        CONSTRAINT auths_users_user
            REFERENCES users
            ON DELETE CASCADE
);

